# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4104dba47e6907998955dab88515e5d51a68e6414db2b6a8267692ff948a78a9a8b4d0429f7f7a30374f37051962399e11dc0991ad605ca775bf6099b901a79b

test:
  secret_key_base: 00631064d98dab4ea1c55a612635f14299651867a18a8d4f16444e759adf5b8df1da3bb175d863a3d2b52e37908c0181e376dd6b5070d637af6b0c4970742ffa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
